### ISSUE TITLE
add arrow damage

### ISSUE THREAD

**Issue by NCPUser** [SpecKeef/Crystal-Addon#1]
from meteor reject

**Comment by 9x00** [comment]
pasta

**Comment by SpecKeef** [comment]
Im not just gonna directly paste it from rejects.

**Comment by SpecKeef** [comment]
I'll have a look and recode it.

**Comment by NCPUser** [comment]
> 

ctrl+v=paste

**Comment by dr-fancy-pants** [comment]
Is this going to be implemented in the future?
