### ISSUE TITLE
do not put credits in the window title bar !!!

### ISSUE THREAD

**Issue by denisapain** [SpecKeef/Crystal-Addon#18]
**Either make it a config option**

[**or just remove it**](https://github.com/SpecKeef/Crystal-Addon/pull/17)

![fuck crystal window title png capture](https://github.com/denisapain/random/blob/main/Screenshot%202023-08-26%20215316.png?raw=true)

**Comment by 9x00** [comment]
Give me a girls discord and i will remove it

**Comment by denisapain** [comment]
> Give me a girls discord and i will remove it

Give me your address and I wont send the fbi to it **uwu**

**Comment by SpecKeef** [comment]
I already didnt allow your pull request on purpose, the credits isnt a big deal. If you are so concerned just download the project and remove it yourself.

**Comment by denisapain** [comment]
> I already didnt allow your pull request on purpose, the credits isnt a big deal. If you are so concerned just download the project and remove it yourself.

fix it to actually build

**Comment by denisapain** [comment]
> I already didnt allow your pull request on purpose, the credits isnt a big deal. If you are so concerned just download the project and remove it yourself.

it also fails if i try to build this repo, not mine, this one

:skull: 

![image](https://github.com/SpecKeef/Crystal-Addon/assets/126583428/6771fa2c-a364-418d-8890-7b56bad0b2fd)

**Comment by GriefUnion** [comment]
lol
