### ISSUE TITLE
Incompatible mod set!

### ISSUE THREAD

**Issue by Topdog1221** [SpecKeef/Crystal-Addon#6]
Multi MC says the mod requires any version of fabric when it is installed. All other addons and meteor client work just fine.

**Comment by Topdog1221** [comment]
![image](https://github.com/SpecKeef/Crystal-Addon/assets/55218279/2e9d0712-893b-4e8d-9d73-874e68858304)

**Comment by SpecKeef** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files
